FROM bitnami/pytorch:1.13.1-debian-11-r20
USER root
RUN pip3 install protobuf==3.14.0 grpcio==1.34.0 grpcio-tools==1.33.1
COPY . /app
RUN pip3 install -r /app/requirements.txt

ENV PYTHONPATH "${PYTHONPATH}:/app"
WORKDIR /app
CMD [ "python3", "scripts/fl_test.py"]
